version: '2'
services:
  uptime:
    image: louislam/uptime-kuma:1.22.1
    restart: unless-stopped
    networks:
      - web
    ports:
      - '3001'
    volumes:
      - uptime:/app/data
    labels:
      - "traefik.http.routers.$SUBDOMAIN.rule=Host(`$SUBDOMAIN.$DOMAIN`)"
      - "traefik.http.services.$SUBDOMAIN.loadbalancer.server.port=3001"
      - "traefik.http.routers.$SUBDOMAIN.middlewares=https-only"
      - "traefik.enable=true"

volumes:
  uptime:

networks:
  web:
    external: true
    name: web