version: '2.1'
services: 
  nocodb: 
    image: "nocodb/nocodb:0.111.4"
    depends_on: 
      nocopgdb: 
        condition: service_healthy
    environment: 
      NC_DB: "pg://nocopgdb:5432?u=$POSTGRES_USER&p=$POSTGRES_PASSWORD&d=$POSTGRES_DB"
    restart: unless-stopped
    volumes: 
      - "nc_data:/usr/app/data"
    labels:
      - "traefik.http.routers.$SUBDOMAIN.rule=Host(`$SUBDOMAIN.$DOMAIN`)"
      - "traefik.http.services.$SUBDOMAIN.loadbalancer.server.port=8080"
      - "traefik.http.routers.$SUBDOMAIN.middlewares=https-only"
      - "traefik.enable=true"
    networks:
      - noco
      - web

  nocopgdb: 
    image: postgres
    environment: 
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    restart: unless-stopped
    volumes: 
      - "nc_db:/var/lib/postgresql/data"
    networks:
      - noco

volumes: 
  nc_db: {}
  nc_data: {}


networks:
  noco:
    internal: true
  web:
    external: true
    name: web