version: "2.1"
services:
  webdav:
    image: ugeek/webdav:arm64
    environment:
      - UDI=1000
      - GID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/sync:/media
      - /opt/volumes/webdav/passwd:/opt/nginx/conf/htpasswd:ro
    networks:
      - web
    ports:
      - 35011:80
    restart: unless-stopped
    labels:
      - "traefik.http.routers.webdav.rule=Host(`$SUBDOMAIN.$DOMAIN`)"
      - "traefik.http.services.webdav.loadbalancer.server.port=80"
      - "traefik.http.routers.${SUBDOMAIN}.middlewares=basic-users,https-only"
      - "traefik.enable=true"

networks:
  web:
    external: true
    name: web
