version: "2.1"
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.26.0-s6
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/sync:/srv
      - /opt/volumes/filebrowser/flatfile.db:/database.db
      - /opt/volumes/filebrowser/.filebrowser.json:/.filebrowser.json
    networks:
      - web
    ports:
      - 35489:80
    restart: unless-stopped
    labels:
      - "traefik.http.routers.filebrowser.rule=Host(`$SUBDOMAIN.$DOMAIN`)"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
      - "traefik.enable=true"

networks:
  web:
    external: true
    name: web
