version: "2"

services:
  wiki:
    image: ghcr.io/linuxserver/dokuwiki:2023-04-04-ls164
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/volumes/doku:/config
    ports:
      - "80"
    restart: unless-stopped
    networks:
      - default
      - web
    labels:
      - "traefik.http.routers.$SUBDOMAIN.rule=Host(`$SUBDOMAIN.$DOMAIN`)"
      - "traefik.http.services.$SUBDOMAIN.loadbalancer.server.port=80"
      - "traefik.http.routers.$SUBDOMAIN.middlewares=https-only"
      - "traefik.enable=true"

networks:
  web:
    external:
      name: web

