version: '3'

services:
  samba:
    image: dperson/samba
    environment:
      - USERID=1000
      - GROUPID=1000
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /opt/sync:/mount
    command: '-s "sync;/mount;yes;no;no;all;none"'
    ports:
      - 139:139
      - 445:445

networks:
  web:
    external:
      name: web
