version: "3"

services:
  maria:
    image: mariadb:11.2
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    restart: unless-stopped
    volumes:
      - /opt/volumes/linkace/maria:/var/lib/mysql
    networks:
     - linkace
    environment:
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE=$MARIADB_DATABASE
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_PASSWORD=$MARIADB_PASSWORD

  linkace:
    image: linkace/linkace:v1.14.1
    restart: unless-stopped
    depends_on:
      - maria
    volumes:
      - /opt/volumes/linkace/logs:/app/storage/logs
    networks:
      - linkace
      - web
    labels:
      - "traefik.http.routers.linkace.rule=Host(`$SUBDOMAIN.$DOMAIN`)"
      - "traefik.http.services.linkace.loadbalancer.server.port=9000"
      - "traefik.enable=true"
    environment:
      - APP_KEY=$APP_KEY
      - DB_HOST=maria
      - DB_DATABASE=$MARIADB_DATABASE
      - DB_USERNAME=$MARIADB_USER
      - DB_PASSWORD=$MARIADB_PASSWORD

networks:
  web:
    external: true
    name: web
  linkace:
    name: linkace
